version: "3.2"

services:
  postgres:
    image: postgres:13.5-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5434:5432'
    volumes:
      - postgres:/var/lib/postgresql/data


  redis:
    image: redis:6.2-alpine


  django:
    restart: always
    command: bash -c "python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis


  celery:
    build: .
    command: celery -A Nimble_test_task worker -l info
    volumes:
      - .:/code
    depends_on:
      - django
      - redis


  celery-beat:
    build: .
    command: celery -A Nimble_test_task beat -l info
    volumes:
      - .:/code
    depends_on:
      - django
      - redis


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


volumes:
  postgres:
    driver: local
  redis:
    driver: local